config/routes.rb
Rails.application.routes.draw do
  # 検索機能
  get "search" => "searches#search", as: "search"

  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index,:show,:update,:destroy]
    resources :posts, only: [:index,:show,:update,:destroy] do
      resources :comments, only: [:update,:destroy]
    end
  end

  # ユーザー側
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'users/my_page' => 'users#show'

    patch 'users/withdraw' => 'users#withdraw'

    resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
      get 'follows' => 'users#follows', as: 'follows'
      get 'followers' => 'users#followers', as: 'followers'
      get 'favorites' => 'users#favorites', as: 'favorites'

    end
    patch 'users/:id/withdraw' => 'user#withdraw'

    resources :posts, only: [:new,:index,:show,:create,:edit,:update,:destroy] do
      resources :comments, only: [:create,:destroy]
      resource :favorite, only: [:create, :destroy]
    end
  end
  # ゲストユーザー
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="vw-100" style="min-height:130px">
  <nav class="navbar navbar-expand-xl navbar-light bg-light fixed-top border-bottom border-dark">
    <!--ロゴ-->
    <% if admin_signed_in? %>
      <a class="navbar-brand justify-content-start" href="/admin/">
        <%= image_tag('header-logo.jpg', style: "max-height: 80px; width: auto;") %>
      </a>
    <% else %>
      <a class="navbar-brand justify-content-start" href="/">
        <%= image_tag('header-logo.jpg', style: "max-height: 80px; width: auto;") %>
      </a>
    <% end %>

    <!-- ログインの表示 -->
    <div class="align-text-center justify-content-center">
      <% if admin_signed_in? %>
        管理者がログイン中
      <% elsif current_user %>
        <%= current_user.name %> さんがログイン中
      <% end %>
    </div>

    <!-- ハンバーガーメニューボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- ナビアイテム -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <!-- 検索フォーム -->
        <div class="align-content-center mr-3">
          <%= render 'searches/search' %>
        </div>
        <!-- adminヘッダー -->
        <% if admin_signed_in? %>
          <li class="nav-item py-1">
            <%= link_to "ユーザー一覧", admin_users_path, class: "nav-link btn btn-outline-secondary users-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to "投稿一覧", admin_posts_path, class: "nav-link btn btn-outline-secondary posts-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link btn btn-outline-secondary logout-btn mr-3" %>
          </li>
        <!-- customersヘッダー -->
        <% elsif user_signed_in? %>
          <li class="nav-item py-1">
            <%= link_to '新しい投稿', new_post_path, class: "nav-link btn btn-outline-secondary new-post-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to "マイページ", users_my_page_path, class: "nav-link btn btn-outline-secondary mypage-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to '投稿一覧', posts_path, class: "nav-link btn btn-outline-secondary posts-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to 'ユーザー一覧', users_path, class: "nav-link btn btn-outline-secondary users-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline-secondary logout-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to 'かんたんSNSとは', about_path, class: "nav-link btn btn-outline-secondary about-btn mr-3" %>
          </li>
        <!-- ログイン前ヘッダー -->
        <% else %>
          <li class="nav-item py-1">
            <%= link_to 'かんたんSNSとは', about_path, class: "nav-link btn btn-outline-secondary about-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to '新規登録', new_user_registration_path, class: "nav-link btn btn-outline-secondary new-user-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to 'ログイン', new_user_session_path, class: "nav-link btn btn-outline-secondary login-user-btn mr-3" %>
          </li>
          <li class="nav-item py-1">
            <%= link_to '管理者ログイン', new_admin_session_path, class: "nav-link btn btn-outline-secondary login-admin-btn mr-3" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasySns</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--fontawesomeを使用可能に-->
    <script src="https://kit.fontawesome.com/196b212b5d.js" crossorigin="anonymous"></script>
    <!--グラフを表示可能に-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <main class="d-flex flex-column min-vh-100">
      <%= render 'layouts/header' %>
      <div class="container flex-grow-1 my-4">
        <%= yield %>
        
        <script>
          $(document).on('turbolinks:load', function() {
            $('.jscroll').jscroll({ // 追加したdivのclass名と合わせる
              contentSelector: '.jscroll',
              nextSelector: '.next a',  // 次ページリンクのセレクタ
              loadingHtml: '読み込み中',
            });
          });
          $('.jscroll').jscroll(jscrollOption);
        </script>
  
      </div>
    </main>

  </body>
</html>